### PR TITLE
Connect four demo with 2 workers

### PR DESCRIPTION
**Pull request by gaudenzkessler**

### CODE REVIEW

**Review by haerdib — COMMENTED** [review]
Do we need 2 connect four demos? I think one should suffice.

**Comment by gaudenzkessler** [comment]
This was requested according to my understanding

**Review by haerdib — COMMENTED** [review]
I see. Then, only a beautifying request: Could you add somewhere the indication to which worker is currently being talked to?

**Review by haerdib — APPROVED** [review]
Thanks, looks good now! 👍

**Pull request merged**
